# Generated by Django 3.0.2 on 2020-06-29 15:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('Borehole', 'Borehole'), ('Pipe', 'Pipe'), ('Well', 'Well')], max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
                ('rooms', models.IntegerField()),
                ('water', multiselectfield.db.fields.MultiSelectField(choices=[('Borehole', 'Borehole'), ('Pipe', 'Pipe'), ('Well', 'Well')], max_length=18)),
                ('bathroom', models.CharField(choices=[('Personal', 'Personal'), ('Shared', 'Shared')], max_length=100)),
                ('garrage', models.BooleanField(default=False)),
                ('image1', models.ImageField(upload_to='house_images')),
                ('image2', models.ImageField(upload_to='house_images')),
                ('image3', models.ImageField(upload_to='house_images')),
                ('image4', models.ImageField(upload_to='house_images')),
                ('image5', models.ImageField(upload_to='house_images')),
            ],
        ),
    ]
