# Generated by Django 3.0.2 on 2020-06-29 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200629_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Owner'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image1',
            field=models.ImageField(null=True, upload_to='house_images'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image2',
            field=models.ImageField(null=True, upload_to='house_images'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image3',
            field=models.ImageField(null=True, upload_to='house_images'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image4',
            field=models.ImageField(null=True, upload_to='house_images'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image5',
            field=models.ImageField(null=True, upload_to='house_images'),
        ),
    ]
