# Generated by Django 3.0.2 on 2020-06-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200629_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='house_images'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='house_images'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='house_images'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='house_images'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='house_images'),
        ),
    ]
