# Generated by Django 3.0.2 on 2020-07-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200706_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='furnishes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
