# Generated by Django 3.0.2 on 2020-07-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_house_no_of_bathrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image1',
            field=models.ImageField(blank=True, default='appartments-logo.png', null=True, upload_to='house_images'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image2',
            field=models.ImageField(blank=True, default='appartments-logo.png', null=True, upload_to='house_images'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image3',
            field=models.ImageField(blank=True, default='appartments-logo.png', null=True, upload_to='house_images'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image4',
            field=models.ImageField(blank=True, default='appartments-logo.png', null=True, upload_to='house_images'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image5',
            field=models.ImageField(blank=True, default='appartments-logo.png', null=True, upload_to='house_images'),
        ),
    ]
