# Generated by Django 3.0.2 on 2020-07-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200708_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='contact',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='rooms',
            field=models.PositiveIntegerField(),
        ),
    ]
