# Generated by Django 3.0.2 on 2020-07-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_house_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='hitcount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
