# Generated by Django 3.0.2 on 2020-07-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200720_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='profile_pic',
            field=models.ImageField(default='user.svg', upload_to=''),
        ),
    ]
