# Generated by Django 3.0.2 on 2020-09-08 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200723_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.House')),
            ],
        ),
    ]
