# Generated by Django 3.0.2 on 2020-09-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='house',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='house',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='house',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='house',
            name='image5',
        ),
    ]
